spring:
    application:
        name: authservice
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
---
spring:
    profiles: dev
    datasource:
        url: ${DB_URL_DEV}
        username: ${DB_USERNAME_DEV}
        password: ${DB_PASSWORD_DEV}
        driver-class-name: org.postgresql.Driver

---
spring:
    profiles: prod
    datasource:
        url: ${DB_URL_PROD}
        username: ${DB_USERNAME_PROD}
        password: ${DB_PASSWORD_PROD}
        driver-class-name: org.postgresql.Driver