name: Workflow CI to skillswap

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >
          --health-cmd "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries=5
          -e POSTGRES_DB=$POSTGRES_DB
          -e POSTGRES_USER=$POSTGRES_USER
          -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt' # pode ser 'zulu', 'temurin', 'adopt', etc.

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Wait for PostgreSQL
      run: |
        while ! pg_isready -h localhost -p 5432 -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }}; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done

    - name: Build with Maven
      env:
        DB_URL_DEV: jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME }}
        DB_USERNAME_DEV: ${{ secrets.DB_USER }}
        DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD }}
      run: mvn -D spring.profiles.active=dev -B package --file AuthService/pom.xml

    - name: Run tests with dev profile
      env:
        DB_URL_DEV: jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME }}
        DB_USERNAME_DEV: ${{ secrets.DB_USER }}
        DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD }}
      run: mvn test -D spring.profiles.active=dev --file AuthService/pom.xml

    - name: List surefire reports
      run: ls -l AuthService/target/surefire-reports/

    - name: Display surefire reports
      run: cat AuthService/target/surefire-reports/*.txt
